### ISSUE TITLE
Illigal adverticement

### ISSUE THREAD

**Issue by danielvistisen** [IgorBuchelnikov/ObservableComputations#15]
Mail address observablecomputations@gmail.com is sending advertisement without consent. Can you confirm this is from here? Mail has been reported to the authorities.

**Comment by IgorBuchelnikov** [comment]
Yes, I confirm sending emails. I do not confirm the emails are Illegal:

* I do not send more than one email to one addressee
* I got email addresses legally from public user profiles
* my emails
  * are targeted to software developers
  * do not contain commercial offers
  * are not anonymous
  * do not contain libel or fraud, do not mislead

For more info, please read https://blog.zoominfo.com/is-cold-email-spam/

**Comment by danielvistisen** [comment]
Read GDPR. Its a marketing mail and I'm an EU citizen.

**Comment by danielvistisen** [comment]
https://blog.zoominfo.com/is-cold-email-spam/
This is a joke right? It's a blog by a company specialized in B2B. Yes you may send cold mails to B2B. NO you may not send it to a private person.

**Comment by IgorBuchelnikov** [comment]
I do not store or disclose your personal data. I use only the data that you yourself have published on one of the sites dedicated to software development. You have published your email address here:

https://app.slack.com/client/T02AG6QJM/C02AJB872/user_profile/U369R0RT9 

If you do not want to receive letters to your email address, do not publish it

**Comment by IgorBuchelnikov** [comment]
Since this issue is not related to the functionality of ObservableComputations, I will delete it
