### ISSUE TITLE
ArgumentOutOfRangeException because comparisonWithMiddleItem > 1

### ISSUE THREAD

**Issue by artemious7** [IgorBuchelnikov/ObservableComputations#17]
Because `comparisonWithMiddleItem` may be a number greater than 1 or smaller than -1 (returned from `IComparer.Compare`), this code will produce an index out of range error.

https://github.com/IgorBuchelnikov/ObservableComputations/blob/3c052a6ac0d525b41832b69e8eb0bdeca702226e/src/ObservableComputations/Collections/Ordering.cs#L716

**Comment by IgorBuchelnikov** [comment]
It would be nice if you add a unit test into SpecialCaseTests.cs file
