### ISSUE TITLE
docs/readme: "FirstCalculating" doesn't exist (should be "FirstComputing"?)

### ISSUE THREAD

**Issue by factormystic** [IgorBuchelnikov/ObservableComputations#3]
Noticed this when looking for the equivalent of `FirstOrDefault`. Maybe it was renamed in the source at some point but the docs are out of date?

**Comment by IgorBuchelnikov** [comment]
You're right. It was renamed to `FirstComputing`. I've fixed it for other operators.
Original name of the project was `Observable**Calculations**`.

**Comment by factormystic** [comment]
Makes sense. Great library btw, not sure why it's not more high profile. It's a great solution for what I would assume is a pretty common problem.
