### ISSUE TITLE
How exactly do you build this?

### ISSUE THREAD

**Issue by asusralis** [IgorBuchelnikov/ObservableComputations#7]
I'm trying to use this into Unity. The .dll from nuget threw errors, so I was going to try and build it myself. However, building has many errors including not being to find ISourceIndexerPropertyTracer, ICanProcessSourceItemKeyChange, ICanProcessSourceItemValueChange... Where are these supposed to be located at?

**Comment by IgorBuchelnikov** [comment]
The current repository version is unstable (I'm working on v.2.0).
Stable versions are in NuGet packages only. 
What version of the NuGet package do you use? 
What error do you encounter? 
Please, provide some code.

**Comment by IgorBuchelnikov** [comment]
If you want to build, check the revision whose comment contains the version of the NuGet package you are using. That revision also contains documention which is actual for the  NuGet package.

**Comment by asusralis** [comment]
Thank you for the help! I was able to build it from the link you sent, and Unity gave no problems.

**Comment by IgorBuchelnikov** [comment]
Please let me know how you fixed the build issue? I want to fix future NuGet packages.

**Comment by asusralis** [comment]
Fixed it for Unity? I just built the project you sent and used the .net standard 2.0 output. The build from the nuget, if I remember correctly, wouldn't load because of a missing dependency or something.

**Comment by IgorBuchelnikov** [comment]
Can you please put here the build log from the NuGet?

**Comment by asusralis** [comment]
Sorry, I didn't see this. I can shortly ) I've been loving this library, by the way; super useful with Noesis GUI!

**Comment by asusralis** [comment]
I get this: 

Unloading broken assembly Assets/Plugins/ObservableComputations/ObservableComputations.dll, this assembly can cause crashes in the runtime

Error: Could not load signature of ObservableComputations.Ordering`2[TSourceItem,TOrderingValue]:get_SortDirectionScalar due to: Could not resolve type with token 01000044 (from typeref, class/assembly System.ComponentModel.ListSortDirection, System.ComponentModel.TypeConverter, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) assembly:System.ComponentModel.TypeConverter, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.ComponentModel.ListSortDirection member:(null) signature:<none>

**Comment by IgorBuchelnikov** [comment]
Thank you for your response! I cannot reproduce the error on my machine, so your additional help is needed. 
Please execute in your app following code:

`			
Assembly assembly = AppDomain.CurrentDomain.GetAssemblies().Single(a => a.FullName.Contains("System.ComponentModel.TypeConverter"));

Console.WriteLine(assembly.CodeBase);
Console.WriteLine(assembly.FullName);
TypeInfo typeInfo = assembly.DefinedTypes.SingleOrDefault(t => t.Name.Contains("ListSortDirection"));
if (typeInfo != null)
    Console.WriteLine(typeInfo.AssemblyQualifiedName);
`
Send me output and System.ComponentModel.TypeConverter.dll assembly located in the directory pointed by "assembly.CodeBase"

**Comment by IgorBuchelnikov** [comment]
There is no response from the issue opener for a long time
