### ISSUE TITLE
Why can't I find the CollectionDispatch() method?

### ISSUE THREAD

**Issue by artemious7** [IgorBuchelnikov/ObservableComputations#8]
The readme file says there's a CollectionDispatch() method to dispatch a collection, but there's none in the NuGet package v1.4.0. Is there any workaround?

**Comment by IgorBuchelnikov** [comment]
CollectionDispatching() method will be included in version 2.0
I plan to release that version soon.

**Comment by artemious7** [comment]
Oh, that's great to know! 
I have just discovered your library and it looks very promising. 
For now, may I download the latest source and use it in my solution as a referenced project?

**Comment by IgorBuchelnikov** [comment]
I think it is better to use 1.4 for now.
The current repository version is unstable and is not documented well.

**Comment by IgorBuchelnikov** [comment]
v 2.0.0 is released with CollectionDispatching() method included
