### ISSUE TITLE
Consider using WeakEventManagers instead of explicit unsubscribe API

### ISSUE THREAD

**Issue by dejfh** [IgorBuchelnikov/ObservableComputations#9]
Have you considered using WeakEventManagers to make the references of events weak, instead of using an explicit unsubscribe API? (See microsoft docs [PropertyChangedEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventmanager?view=net-5.0), [CollectionChangedEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.collectionchangedeventmanager?view=net-5.0) and [Weak Event Patterns](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/weak-event-patterns?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-5.0)) I do not know, but I would expect that Microsoft came up with something that has no (or few) garbage collection issues.

Introducing an unsubscribe API would require all classes using this library implementing IDisposable (or something similar), right?

I hope this is an option for you, because I really like this library and not having to unsubscribe makes it so much nicer to use.

**Comment by IgorBuchelnikov** [comment]
[PropertyChangedEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventmanager?view=net-5.0), [CollectionChangedEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.collectionchangedeventmanager?view=net-5.0) are located in the WindowsBase.dll (WPF) assembly. My guess is that these classes are guaranteed to work well in WPF and not on other platforms. ObservableComputations is cross-platform and targets not only WPF but Xamarin and Blazor as well.
In ObservableComputations 2.0, the only class that implements IDisposable is Consumer (there is also a Binding class, but this is not part of the core functionality). I agree that automatic unsubscription is more convenient. Hopefully the new unsubscribe API will not bring any significant complications.

**Comment by dejfh** [comment]
Oh, I was not aware, that those classes are Windows/WPF specific. My bad. The argument about cross-platform compatibility is well taken. I'm curious to see, what your API will look like.
